/*
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiCallback;
import com.invoicepdfs.ApiClient;
import com.invoicepdfs.ApiException;
import com.invoicepdfs.ApiResponse;
import com.invoicepdfs.Configuration;
import com.invoicepdfs.Pair;
import com.invoicepdfs.ProgressRequestBody;
import com.invoicepdfs.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.SimpleBoolResponse;
import org.openapitools.client.model.WorkspaceCreateRequest;
import org.openapitools.client.model.WorkspaceMemberCreateRequest;
import org.openapitools.client.model.WorkspaceMemberOut;
import org.openapitools.client.model.WorkspaceMemberPatchRequest;
import org.openapitools.client.model.WorkspaceMembersListResponse;
import org.openapitools.client.model.WorkspacePatchRequest;
import org.openapitools.client.model.WorkspaceResponse;
import org.openapitools.client.model.WorkspacesListResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WorkspacesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public WorkspacesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WorkspacesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createMemberApiV1WorkspacesWorkspaceIdMembersPost
     * @param workspaceId  (required)
     * @param workspaceMemberCreateRequest  (required)
     * @param idempotencyKey  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createMemberApiV1WorkspacesWorkspaceIdMembersPostCall(String workspaceId, WorkspaceMemberCreateRequest workspaceMemberCreateRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = workspaceMemberCreateRequest;

        // create path and map variables
        String localVarPath = "/api/v1/workspaces/{workspace_id}/members"
            .replace("{" + "workspace_id" + "}", localVarApiClient.escapeString(workspaceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createMemberApiV1WorkspacesWorkspaceIdMembersPostValidateBeforeCall(String workspaceId, WorkspaceMemberCreateRequest workspaceMemberCreateRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling createMemberApiV1WorkspacesWorkspaceIdMembersPost(Async)");
        }

        // verify the required parameter 'workspaceMemberCreateRequest' is set
        if (workspaceMemberCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'workspaceMemberCreateRequest' when calling createMemberApiV1WorkspacesWorkspaceIdMembersPost(Async)");
        }

        return createMemberApiV1WorkspacesWorkspaceIdMembersPostCall(workspaceId, workspaceMemberCreateRequest, idempotencyKey, _callback);

    }

    /**
     * Create Member
     * 
     * @param workspaceId  (required)
     * @param workspaceMemberCreateRequest  (required)
     * @param idempotencyKey  (optional)
     * @return WorkspaceMembersListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public WorkspaceMembersListResponse createMemberApiV1WorkspacesWorkspaceIdMembersPost(String workspaceId, WorkspaceMemberCreateRequest workspaceMemberCreateRequest, String idempotencyKey) throws ApiException {
        ApiResponse<WorkspaceMembersListResponse> localVarResp = createMemberApiV1WorkspacesWorkspaceIdMembersPostWithHttpInfo(workspaceId, workspaceMemberCreateRequest, idempotencyKey);
        return localVarResp.getData();
    }

    /**
     * Create Member
     * 
     * @param workspaceId  (required)
     * @param workspaceMemberCreateRequest  (required)
     * @param idempotencyKey  (optional)
     * @return ApiResponse&lt;WorkspaceMembersListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkspaceMembersListResponse> createMemberApiV1WorkspacesWorkspaceIdMembersPostWithHttpInfo(String workspaceId, WorkspaceMemberCreateRequest workspaceMemberCreateRequest, String idempotencyKey) throws ApiException {
        okhttp3.Call localVarCall = createMemberApiV1WorkspacesWorkspaceIdMembersPostValidateBeforeCall(workspaceId, workspaceMemberCreateRequest, idempotencyKey, null);
        Type localVarReturnType = new TypeToken<WorkspaceMembersListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Member (asynchronously)
     * 
     * @param workspaceId  (required)
     * @param workspaceMemberCreateRequest  (required)
     * @param idempotencyKey  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createMemberApiV1WorkspacesWorkspaceIdMembersPostAsync(String workspaceId, WorkspaceMemberCreateRequest workspaceMemberCreateRequest, String idempotencyKey, final ApiCallback<WorkspaceMembersListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createMemberApiV1WorkspacesWorkspaceIdMembersPostValidateBeforeCall(workspaceId, workspaceMemberCreateRequest, idempotencyKey, _callback);
        Type localVarReturnType = new TypeToken<WorkspaceMembersListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createWorkspaceApiV1WorkspacesPost
     * @param workspaceCreateRequest  (required)
     * @param idempotencyKey  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createWorkspaceApiV1WorkspacesPostCall(WorkspaceCreateRequest workspaceCreateRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = workspaceCreateRequest;

        // create path and map variables
        String localVarPath = "/api/v1/workspaces";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createWorkspaceApiV1WorkspacesPostValidateBeforeCall(WorkspaceCreateRequest workspaceCreateRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceCreateRequest' is set
        if (workspaceCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'workspaceCreateRequest' when calling createWorkspaceApiV1WorkspacesPost(Async)");
        }

        return createWorkspaceApiV1WorkspacesPostCall(workspaceCreateRequest, idempotencyKey, _callback);

    }

    /**
     * Create Workspace
     * 
     * @param workspaceCreateRequest  (required)
     * @param idempotencyKey  (optional)
     * @return WorkspaceResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public WorkspaceResponse createWorkspaceApiV1WorkspacesPost(WorkspaceCreateRequest workspaceCreateRequest, String idempotencyKey) throws ApiException {
        ApiResponse<WorkspaceResponse> localVarResp = createWorkspaceApiV1WorkspacesPostWithHttpInfo(workspaceCreateRequest, idempotencyKey);
        return localVarResp.getData();
    }

    /**
     * Create Workspace
     * 
     * @param workspaceCreateRequest  (required)
     * @param idempotencyKey  (optional)
     * @return ApiResponse&lt;WorkspaceResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkspaceResponse> createWorkspaceApiV1WorkspacesPostWithHttpInfo(WorkspaceCreateRequest workspaceCreateRequest, String idempotencyKey) throws ApiException {
        okhttp3.Call localVarCall = createWorkspaceApiV1WorkspacesPostValidateBeforeCall(workspaceCreateRequest, idempotencyKey, null);
        Type localVarReturnType = new TypeToken<WorkspaceResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Workspace (asynchronously)
     * 
     * @param workspaceCreateRequest  (required)
     * @param idempotencyKey  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createWorkspaceApiV1WorkspacesPostAsync(WorkspaceCreateRequest workspaceCreateRequest, String idempotencyKey, final ApiCallback<WorkspaceResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createWorkspaceApiV1WorkspacesPostValidateBeforeCall(workspaceCreateRequest, idempotencyKey, _callback);
        Type localVarReturnType = new TypeToken<WorkspaceResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDelete
     * @param workspaceId  (required)
     * @param memberId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDeleteCall(String workspaceId, String memberId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/workspaces/{workspace_id}/members/{member_id}"
            .replace("{" + "workspace_id" + "}", localVarApiClient.escapeString(workspaceId.toString()))
            .replace("{" + "member_id" + "}", localVarApiClient.escapeString(memberId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDeleteValidateBeforeCall(String workspaceId, String memberId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDelete(Async)");
        }

        // verify the required parameter 'memberId' is set
        if (memberId == null) {
            throw new ApiException("Missing the required parameter 'memberId' when calling deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDelete(Async)");
        }

        return deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDeleteCall(workspaceId, memberId, _callback);

    }

    /**
     * Delete Member
     * 
     * @param workspaceId  (required)
     * @param memberId  (required)
     * @return SimpleBoolResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public SimpleBoolResponse deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDelete(String workspaceId, String memberId) throws ApiException {
        ApiResponse<SimpleBoolResponse> localVarResp = deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDeleteWithHttpInfo(workspaceId, memberId);
        return localVarResp.getData();
    }

    /**
     * Delete Member
     * 
     * @param workspaceId  (required)
     * @param memberId  (required)
     * @return ApiResponse&lt;SimpleBoolResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SimpleBoolResponse> deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDeleteWithHttpInfo(String workspaceId, String memberId) throws ApiException {
        okhttp3.Call localVarCall = deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDeleteValidateBeforeCall(workspaceId, memberId, null);
        Type localVarReturnType = new TypeToken<SimpleBoolResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete Member (asynchronously)
     * 
     * @param workspaceId  (required)
     * @param memberId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDeleteAsync(String workspaceId, String memberId, final ApiCallback<SimpleBoolResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteMemberApiV1WorkspacesWorkspaceIdMembersMemberIdDeleteValidateBeforeCall(workspaceId, memberId, _callback);
        Type localVarReturnType = new TypeToken<SimpleBoolResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteWorkspaceApiV1WorkspacesWorkspaceIdDelete
     * @param workspaceId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWorkspaceApiV1WorkspacesWorkspaceIdDeleteCall(String workspaceId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/workspaces/{workspace_id}"
            .replace("{" + "workspace_id" + "}", localVarApiClient.escapeString(workspaceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteWorkspaceApiV1WorkspacesWorkspaceIdDeleteValidateBeforeCall(String workspaceId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling deleteWorkspaceApiV1WorkspacesWorkspaceIdDelete(Async)");
        }

        return deleteWorkspaceApiV1WorkspacesWorkspaceIdDeleteCall(workspaceId, _callback);

    }

    /**
     * Delete Workspace
     * 
     * @param workspaceId  (required)
     * @return SimpleBoolResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public SimpleBoolResponse deleteWorkspaceApiV1WorkspacesWorkspaceIdDelete(String workspaceId) throws ApiException {
        ApiResponse<SimpleBoolResponse> localVarResp = deleteWorkspaceApiV1WorkspacesWorkspaceIdDeleteWithHttpInfo(workspaceId);
        return localVarResp.getData();
    }

    /**
     * Delete Workspace
     * 
     * @param workspaceId  (required)
     * @return ApiResponse&lt;SimpleBoolResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SimpleBoolResponse> deleteWorkspaceApiV1WorkspacesWorkspaceIdDeleteWithHttpInfo(String workspaceId) throws ApiException {
        okhttp3.Call localVarCall = deleteWorkspaceApiV1WorkspacesWorkspaceIdDeleteValidateBeforeCall(workspaceId, null);
        Type localVarReturnType = new TypeToken<SimpleBoolResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete Workspace (asynchronously)
     * 
     * @param workspaceId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWorkspaceApiV1WorkspacesWorkspaceIdDeleteAsync(String workspaceId, final ApiCallback<SimpleBoolResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteWorkspaceApiV1WorkspacesWorkspaceIdDeleteValidateBeforeCall(workspaceId, _callback);
        Type localVarReturnType = new TypeToken<SimpleBoolResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getWorkspaceApiV1WorkspacesWorkspaceIdGet
     * @param workspaceId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getWorkspaceApiV1WorkspacesWorkspaceIdGetCall(String workspaceId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/workspaces/{workspace_id}"
            .replace("{" + "workspace_id" + "}", localVarApiClient.escapeString(workspaceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getWorkspaceApiV1WorkspacesWorkspaceIdGetValidateBeforeCall(String workspaceId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling getWorkspaceApiV1WorkspacesWorkspaceIdGet(Async)");
        }

        return getWorkspaceApiV1WorkspacesWorkspaceIdGetCall(workspaceId, _callback);

    }

    /**
     * Get Workspace
     * 
     * @param workspaceId  (required)
     * @return WorkspaceResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public WorkspaceResponse getWorkspaceApiV1WorkspacesWorkspaceIdGet(String workspaceId) throws ApiException {
        ApiResponse<WorkspaceResponse> localVarResp = getWorkspaceApiV1WorkspacesWorkspaceIdGetWithHttpInfo(workspaceId);
        return localVarResp.getData();
    }

    /**
     * Get Workspace
     * 
     * @param workspaceId  (required)
     * @return ApiResponse&lt;WorkspaceResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkspaceResponse> getWorkspaceApiV1WorkspacesWorkspaceIdGetWithHttpInfo(String workspaceId) throws ApiException {
        okhttp3.Call localVarCall = getWorkspaceApiV1WorkspacesWorkspaceIdGetValidateBeforeCall(workspaceId, null);
        Type localVarReturnType = new TypeToken<WorkspaceResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Workspace (asynchronously)
     * 
     * @param workspaceId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getWorkspaceApiV1WorkspacesWorkspaceIdGetAsync(String workspaceId, final ApiCallback<WorkspaceResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getWorkspaceApiV1WorkspacesWorkspaceIdGetValidateBeforeCall(workspaceId, _callback);
        Type localVarReturnType = new TypeToken<WorkspaceResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listMembersApiV1WorkspacesWorkspaceIdMembersGet
     * @param workspaceId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listMembersApiV1WorkspacesWorkspaceIdMembersGetCall(String workspaceId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/workspaces/{workspace_id}/members"
            .replace("{" + "workspace_id" + "}", localVarApiClient.escapeString(workspaceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listMembersApiV1WorkspacesWorkspaceIdMembersGetValidateBeforeCall(String workspaceId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling listMembersApiV1WorkspacesWorkspaceIdMembersGet(Async)");
        }

        return listMembersApiV1WorkspacesWorkspaceIdMembersGetCall(workspaceId, _callback);

    }

    /**
     * List Members
     * 
     * @param workspaceId  (required)
     * @return WorkspaceMembersListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public WorkspaceMembersListResponse listMembersApiV1WorkspacesWorkspaceIdMembersGet(String workspaceId) throws ApiException {
        ApiResponse<WorkspaceMembersListResponse> localVarResp = listMembersApiV1WorkspacesWorkspaceIdMembersGetWithHttpInfo(workspaceId);
        return localVarResp.getData();
    }

    /**
     * List Members
     * 
     * @param workspaceId  (required)
     * @return ApiResponse&lt;WorkspaceMembersListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkspaceMembersListResponse> listMembersApiV1WorkspacesWorkspaceIdMembersGetWithHttpInfo(String workspaceId) throws ApiException {
        okhttp3.Call localVarCall = listMembersApiV1WorkspacesWorkspaceIdMembersGetValidateBeforeCall(workspaceId, null);
        Type localVarReturnType = new TypeToken<WorkspaceMembersListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Members (asynchronously)
     * 
     * @param workspaceId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listMembersApiV1WorkspacesWorkspaceIdMembersGetAsync(String workspaceId, final ApiCallback<WorkspaceMembersListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listMembersApiV1WorkspacesWorkspaceIdMembersGetValidateBeforeCall(workspaceId, _callback);
        Type localVarReturnType = new TypeToken<WorkspaceMembersListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listWorkspacesApiV1WorkspacesGet
     * @param limit  (optional, default to 50)
     * @param cursor  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWorkspacesApiV1WorkspacesGetCall(Integer limit, String cursor, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/workspaces";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listWorkspacesApiV1WorkspacesGetValidateBeforeCall(Integer limit, String cursor, final ApiCallback _callback) throws ApiException {
        return listWorkspacesApiV1WorkspacesGetCall(limit, cursor, _callback);

    }

    /**
     * List Workspaces
     * 
     * @param limit  (optional, default to 50)
     * @param cursor  (optional)
     * @return WorkspacesListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public WorkspacesListResponse listWorkspacesApiV1WorkspacesGet(Integer limit, String cursor) throws ApiException {
        ApiResponse<WorkspacesListResponse> localVarResp = listWorkspacesApiV1WorkspacesGetWithHttpInfo(limit, cursor);
        return localVarResp.getData();
    }

    /**
     * List Workspaces
     * 
     * @param limit  (optional, default to 50)
     * @param cursor  (optional)
     * @return ApiResponse&lt;WorkspacesListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkspacesListResponse> listWorkspacesApiV1WorkspacesGetWithHttpInfo(Integer limit, String cursor) throws ApiException {
        okhttp3.Call localVarCall = listWorkspacesApiV1WorkspacesGetValidateBeforeCall(limit, cursor, null);
        Type localVarReturnType = new TypeToken<WorkspacesListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Workspaces (asynchronously)
     * 
     * @param limit  (optional, default to 50)
     * @param cursor  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWorkspacesApiV1WorkspacesGetAsync(Integer limit, String cursor, final ApiCallback<WorkspacesListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listWorkspacesApiV1WorkspacesGetValidateBeforeCall(limit, cursor, _callback);
        Type localVarReturnType = new TypeToken<WorkspacesListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatch
     * @param workspaceId  (required)
     * @param memberId  (required)
     * @param workspaceMemberPatchRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatchCall(String workspaceId, String memberId, WorkspaceMemberPatchRequest workspaceMemberPatchRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = workspaceMemberPatchRequest;

        // create path and map variables
        String localVarPath = "/api/v1/workspaces/{workspace_id}/members/{member_id}"
            .replace("{" + "workspace_id" + "}", localVarApiClient.escapeString(workspaceId.toString()))
            .replace("{" + "member_id" + "}", localVarApiClient.escapeString(memberId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatchValidateBeforeCall(String workspaceId, String memberId, WorkspaceMemberPatchRequest workspaceMemberPatchRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatch(Async)");
        }

        // verify the required parameter 'memberId' is set
        if (memberId == null) {
            throw new ApiException("Missing the required parameter 'memberId' when calling patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatch(Async)");
        }

        // verify the required parameter 'workspaceMemberPatchRequest' is set
        if (workspaceMemberPatchRequest == null) {
            throw new ApiException("Missing the required parameter 'workspaceMemberPatchRequest' when calling patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatch(Async)");
        }

        return patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatchCall(workspaceId, memberId, workspaceMemberPatchRequest, _callback);

    }

    /**
     * Patch Member
     * 
     * @param workspaceId  (required)
     * @param memberId  (required)
     * @param workspaceMemberPatchRequest  (required)
     * @return WorkspaceMemberOut
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public WorkspaceMemberOut patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatch(String workspaceId, String memberId, WorkspaceMemberPatchRequest workspaceMemberPatchRequest) throws ApiException {
        ApiResponse<WorkspaceMemberOut> localVarResp = patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatchWithHttpInfo(workspaceId, memberId, workspaceMemberPatchRequest);
        return localVarResp.getData();
    }

    /**
     * Patch Member
     * 
     * @param workspaceId  (required)
     * @param memberId  (required)
     * @param workspaceMemberPatchRequest  (required)
     * @return ApiResponse&lt;WorkspaceMemberOut&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkspaceMemberOut> patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatchWithHttpInfo(String workspaceId, String memberId, WorkspaceMemberPatchRequest workspaceMemberPatchRequest) throws ApiException {
        okhttp3.Call localVarCall = patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatchValidateBeforeCall(workspaceId, memberId, workspaceMemberPatchRequest, null);
        Type localVarReturnType = new TypeToken<WorkspaceMemberOut>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Patch Member (asynchronously)
     * 
     * @param workspaceId  (required)
     * @param memberId  (required)
     * @param workspaceMemberPatchRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatchAsync(String workspaceId, String memberId, WorkspaceMemberPatchRequest workspaceMemberPatchRequest, final ApiCallback<WorkspaceMemberOut> _callback) throws ApiException {

        okhttp3.Call localVarCall = patchMemberApiV1WorkspacesWorkspaceIdMembersMemberIdPatchValidateBeforeCall(workspaceId, memberId, workspaceMemberPatchRequest, _callback);
        Type localVarReturnType = new TypeToken<WorkspaceMemberOut>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for patchWorkspaceApiV1WorkspacesWorkspaceIdPatch
     * @param workspaceId  (required)
     * @param workspacePatchRequest  (required)
     * @param idempotencyKey  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchWorkspaceApiV1WorkspacesWorkspaceIdPatchCall(String workspaceId, WorkspacePatchRequest workspacePatchRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = workspacePatchRequest;

        // create path and map variables
        String localVarPath = "/api/v1/workspaces/{workspace_id}"
            .replace("{" + "workspace_id" + "}", localVarApiClient.escapeString(workspaceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call patchWorkspaceApiV1WorkspacesWorkspaceIdPatchValidateBeforeCall(String workspaceId, WorkspacePatchRequest workspacePatchRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'workspaceId' is set
        if (workspaceId == null) {
            throw new ApiException("Missing the required parameter 'workspaceId' when calling patchWorkspaceApiV1WorkspacesWorkspaceIdPatch(Async)");
        }

        // verify the required parameter 'workspacePatchRequest' is set
        if (workspacePatchRequest == null) {
            throw new ApiException("Missing the required parameter 'workspacePatchRequest' when calling patchWorkspaceApiV1WorkspacesWorkspaceIdPatch(Async)");
        }

        return patchWorkspaceApiV1WorkspacesWorkspaceIdPatchCall(workspaceId, workspacePatchRequest, idempotencyKey, _callback);

    }

    /**
     * Patch Workspace
     * 
     * @param workspaceId  (required)
     * @param workspacePatchRequest  (required)
     * @param idempotencyKey  (optional)
     * @return WorkspaceResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public WorkspaceResponse patchWorkspaceApiV1WorkspacesWorkspaceIdPatch(String workspaceId, WorkspacePatchRequest workspacePatchRequest, String idempotencyKey) throws ApiException {
        ApiResponse<WorkspaceResponse> localVarResp = patchWorkspaceApiV1WorkspacesWorkspaceIdPatchWithHttpInfo(workspaceId, workspacePatchRequest, idempotencyKey);
        return localVarResp.getData();
    }

    /**
     * Patch Workspace
     * 
     * @param workspaceId  (required)
     * @param workspacePatchRequest  (required)
     * @param idempotencyKey  (optional)
     * @return ApiResponse&lt;WorkspaceResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkspaceResponse> patchWorkspaceApiV1WorkspacesWorkspaceIdPatchWithHttpInfo(String workspaceId, WorkspacePatchRequest workspacePatchRequest, String idempotencyKey) throws ApiException {
        okhttp3.Call localVarCall = patchWorkspaceApiV1WorkspacesWorkspaceIdPatchValidateBeforeCall(workspaceId, workspacePatchRequest, idempotencyKey, null);
        Type localVarReturnType = new TypeToken<WorkspaceResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Patch Workspace (asynchronously)
     * 
     * @param workspaceId  (required)
     * @param workspacePatchRequest  (required)
     * @param idempotencyKey  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchWorkspaceApiV1WorkspacesWorkspaceIdPatchAsync(String workspaceId, WorkspacePatchRequest workspacePatchRequest, String idempotencyKey, final ApiCallback<WorkspaceResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = patchWorkspaceApiV1WorkspacesWorkspaceIdPatchValidateBeforeCall(workspaceId, workspacePatchRequest, idempotencyKey, _callback);
        Type localVarReturnType = new TypeToken<WorkspaceResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
