/*
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.MoneyOut;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoiceTotalsOut
 */
public class InvoiceTotalsOutTest {
    private final InvoiceTotalsOut model = new InvoiceTotalsOut();

    /**
     * Model tests for InvoiceTotalsOut
     */
    @Test
    public void testInvoiceTotalsOut() {
        // TODO: test InvoiceTotalsOut
    }

    /**
     * Test the property 'subtotal'
     */
    @Test
    public void subtotalTest() {
        // TODO: test subtotal
    }

    /**
     * Test the property 'discountTotal'
     */
    @Test
    public void discountTotalTest() {
        // TODO: test discountTotal
    }

    /**
     * Test the property 'taxTotal'
     */
    @Test
    public void taxTotalTest() {
        // TODO: test taxTotal
    }

    /**
     * Test the property 'shippingTotal'
     */
    @Test
    public void shippingTotalTest() {
        // TODO: test shippingTotal
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
