/*
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.invoicepdfs.JSON;

/**
 * BrandingProfilePatchRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-14T21:07:01.111249349Z[Etc/UTC]", comments = "Generator version: 7.7.0")
public class BrandingProfilePatchRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PRIMARY_COLOR = "primary_color";
  @SerializedName(SERIALIZED_NAME_PRIMARY_COLOR)
  private String primaryColor;

  public static final String SERIALIZED_NAME_ACCENT_COLOR = "accent_color";
  @SerializedName(SERIALIZED_NAME_ACCENT_COLOR)
  private String accentColor;

  public static final String SERIALIZED_NAME_FONT_FAMILY = "font_family";
  @SerializedName(SERIALIZED_NAME_FONT_FAMILY)
  private String fontFamily;

  public static final String SERIALIZED_NAME_HEADER_TEXT = "header_text";
  @SerializedName(SERIALIZED_NAME_HEADER_TEXT)
  private String headerText;

  public static final String SERIALIZED_NAME_FOOTER_TEXT = "footer_text";
  @SerializedName(SERIALIZED_NAME_FOOTER_TEXT)
  private String footerText;

  public static final String SERIALIZED_NAME_HIDE_INVOICEPDFS_BRANDING = "hide_invoicepdfs_branding";
  @SerializedName(SERIALIZED_NAME_HIDE_INVOICEPDFS_BRANDING)
  private Boolean hideInvoicepdfsBranding;

  public static final String SERIALIZED_NAME_IS_DEFAULT = "is_default";
  @SerializedName(SERIALIZED_NAME_IS_DEFAULT)
  private Boolean isDefault;

  public BrandingProfilePatchRequest() {
  }

  public BrandingProfilePatchRequest name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public BrandingProfilePatchRequest primaryColor(String primaryColor) {
    this.primaryColor = primaryColor;
    return this;
  }

  /**
   * Get primaryColor
   * @return primaryColor
   */
  @javax.annotation.Nullable
  public String getPrimaryColor() {
    return primaryColor;
  }

  public void setPrimaryColor(String primaryColor) {
    this.primaryColor = primaryColor;
  }


  public BrandingProfilePatchRequest accentColor(String accentColor) {
    this.accentColor = accentColor;
    return this;
  }

  /**
   * Get accentColor
   * @return accentColor
   */
  @javax.annotation.Nullable
  public String getAccentColor() {
    return accentColor;
  }

  public void setAccentColor(String accentColor) {
    this.accentColor = accentColor;
  }


  public BrandingProfilePatchRequest fontFamily(String fontFamily) {
    this.fontFamily = fontFamily;
    return this;
  }

  /**
   * Get fontFamily
   * @return fontFamily
   */
  @javax.annotation.Nullable
  public String getFontFamily() {
    return fontFamily;
  }

  public void setFontFamily(String fontFamily) {
    this.fontFamily = fontFamily;
  }


  public BrandingProfilePatchRequest headerText(String headerText) {
    this.headerText = headerText;
    return this;
  }

  /**
   * Get headerText
   * @return headerText
   */
  @javax.annotation.Nullable
  public String getHeaderText() {
    return headerText;
  }

  public void setHeaderText(String headerText) {
    this.headerText = headerText;
  }


  public BrandingProfilePatchRequest footerText(String footerText) {
    this.footerText = footerText;
    return this;
  }

  /**
   * Get footerText
   * @return footerText
   */
  @javax.annotation.Nullable
  public String getFooterText() {
    return footerText;
  }

  public void setFooterText(String footerText) {
    this.footerText = footerText;
  }


  public BrandingProfilePatchRequest hideInvoicepdfsBranding(Boolean hideInvoicepdfsBranding) {
    this.hideInvoicepdfsBranding = hideInvoicepdfsBranding;
    return this;
  }

  /**
   * Get hideInvoicepdfsBranding
   * @return hideInvoicepdfsBranding
   */
  @javax.annotation.Nullable
  public Boolean getHideInvoicepdfsBranding() {
    return hideInvoicepdfsBranding;
  }

  public void setHideInvoicepdfsBranding(Boolean hideInvoicepdfsBranding) {
    this.hideInvoicepdfsBranding = hideInvoicepdfsBranding;
  }


  public BrandingProfilePatchRequest isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

  /**
   * Get isDefault
   * @return isDefault
   */
  @javax.annotation.Nullable
  public Boolean getIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrandingProfilePatchRequest brandingProfilePatchRequest = (BrandingProfilePatchRequest) o;
    return Objects.equals(this.name, brandingProfilePatchRequest.name) &&
        Objects.equals(this.primaryColor, brandingProfilePatchRequest.primaryColor) &&
        Objects.equals(this.accentColor, brandingProfilePatchRequest.accentColor) &&
        Objects.equals(this.fontFamily, brandingProfilePatchRequest.fontFamily) &&
        Objects.equals(this.headerText, brandingProfilePatchRequest.headerText) &&
        Objects.equals(this.footerText, brandingProfilePatchRequest.footerText) &&
        Objects.equals(this.hideInvoicepdfsBranding, brandingProfilePatchRequest.hideInvoicepdfsBranding) &&
        Objects.equals(this.isDefault, brandingProfilePatchRequest.isDefault);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, primaryColor, accentColor, fontFamily, headerText, footerText, hideInvoicepdfsBranding, isDefault);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrandingProfilePatchRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    primaryColor: ").append(toIndentedString(primaryColor)).append("\n");
    sb.append("    accentColor: ").append(toIndentedString(accentColor)).append("\n");
    sb.append("    fontFamily: ").append(toIndentedString(fontFamily)).append("\n");
    sb.append("    headerText: ").append(toIndentedString(headerText)).append("\n");
    sb.append("    footerText: ").append(toIndentedString(footerText)).append("\n");
    sb.append("    hideInvoicepdfsBranding: ").append(toIndentedString(hideInvoicepdfsBranding)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("primary_color");
    openapiFields.add("accent_color");
    openapiFields.add("font_family");
    openapiFields.add("header_text");
    openapiFields.add("footer_text");
    openapiFields.add("hide_invoicepdfs_branding");
    openapiFields.add("is_default");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BrandingProfilePatchRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BrandingProfilePatchRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BrandingProfilePatchRequest is not found in the empty JSON string", BrandingProfilePatchRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BrandingProfilePatchRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BrandingProfilePatchRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("primary_color") != null && !jsonObj.get("primary_color").isJsonNull()) && !jsonObj.get("primary_color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `primary_color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primary_color").toString()));
      }
      if ((jsonObj.get("accent_color") != null && !jsonObj.get("accent_color").isJsonNull()) && !jsonObj.get("accent_color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accent_color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accent_color").toString()));
      }
      if ((jsonObj.get("font_family") != null && !jsonObj.get("font_family").isJsonNull()) && !jsonObj.get("font_family").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `font_family` to be a primitive type in the JSON string but got `%s`", jsonObj.get("font_family").toString()));
      }
      if ((jsonObj.get("header_text") != null && !jsonObj.get("header_text").isJsonNull()) && !jsonObj.get("header_text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `header_text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("header_text").toString()));
      }
      if ((jsonObj.get("footer_text") != null && !jsonObj.get("footer_text").isJsonNull()) && !jsonObj.get("footer_text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `footer_text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("footer_text").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BrandingProfilePatchRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BrandingProfilePatchRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BrandingProfilePatchRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BrandingProfilePatchRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<BrandingProfilePatchRequest>() {
           @Override
           public void write(JsonWriter out, BrandingProfilePatchRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BrandingProfilePatchRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BrandingProfilePatchRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BrandingProfilePatchRequest
   * @throws IOException if the JSON string is invalid with respect to BrandingProfilePatchRequest
   */
  public static BrandingProfilePatchRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BrandingProfilePatchRequest.class);
  }

  /**
   * Convert an instance of BrandingProfilePatchRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

