/*
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * &#x60;completed&#x60; is the schedule running out, not a failure — set by app/recurring/processor.py when the end date or occurrence count is reached. &#x60;RecurringInvoiceOut.status&#x60; was an unconstrained &#x60;str&#x60;, so this is the first time the set has been written down anywhere.
 */
@JsonAdapter(RecurringInvoiceStatus.Adapter.class)
public enum RecurringInvoiceStatus {
  
  ACTIVE("active"),
  
  PAUSED("paused"),
  
  CANCELLED("cancelled"),
  
  COMPLETED("completed");

  private String value;

  RecurringInvoiceStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RecurringInvoiceStatus fromValue(String value) {
    for (RecurringInvoiceStatus b : RecurringInvoiceStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RecurringInvoiceStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final RecurringInvoiceStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RecurringInvoiceStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RecurringInvoiceStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    RecurringInvoiceStatus.fromValue(value);
  }
}

