/*
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.ApiErrorResponse;
import org.openapitools.client.model.ApiKeyCreateRequest;
import org.openapitools.client.model.ApiKeyCreateResponse;
import org.openapitools.client.model.ApiKeyDetailResponse;
import org.openapitools.client.model.ApiKeyListResponse;
import org.openapitools.client.model.ApiKeyPatchRequest;
import org.openapitools.client.model.ApiKeyRevokeResponse;
import org.openapitools.client.model.ApiKeyRotateResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiKeysApi
 */
@Disabled
public class ApiKeysApiTest {

    private final ApiKeysApi api = new ApiKeysApi();

    /**
     * Create Api Key
     *
     * Create an API key and return it once.  The response is the only place the key appears — it is stored hashed, so a lost key cannot be recovered, only replaced.  Keys are not scoped: any key can do anything this account can, including creating further keys and deleting data. Treat one as a full credential.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createApiKeyTest() throws ApiException {
        ApiKeyCreateRequest apiKeyCreateRequest = null;
        ApiKeyCreateResponse response = api.createApiKey(apiKeyCreateRequest);
        // TODO: test validations
    }

    /**
     * Get Api Key
     *
     * One API key&#39;s details by id, without the key itself.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getApiKeyTest() throws ApiException {
        String apiKeyId = null;
        ApiKeyDetailResponse response = api.getApiKey(apiKeyId);
        // TODO: test validations
    }

    /**
     * List Api Keys
     *
     * Every API key on the account, including revoked ones.  Shows only the last four characters: the key itself is stored hashed and cannot be recovered.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listApiKeysTest() throws ApiException {
        ApiKeyListResponse response = api.listApiKeys();
        // TODO: test validations
    }

    /**
     * Revoke Api Key
     *
     * Stop an API key working, permanently.  Takes effect immediately and cannot be undone — issue a new key with &#x60;create_api_key&#x60; instead. The record is kept, so the key still appears in &#x60;list_api_keys&#x60; with a revoked date and the audit log stays readable.  Revoking an already-revoked key succeeds and changes nothing.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void revokeApiKeyTest() throws ApiException {
        String apiKeyId = null;
        ApiKeyRevokeResponse response = api.revokeApiKey(apiKeyId);
        // TODO: test validations
    }

    /**
     * Rotate Api Key
     *
     * Revoke the existing key and create a new one with the same name.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rotateApiKeyTest() throws ApiException {
        String apiKeyId = null;
        ApiKeyRotateResponse response = api.rotateApiKey(apiKeyId);
        // TODO: test validations
    }

    /**
     * Update Api Key
     *
     * Rename an API key.  The key itself is unchanged and keeps working. To replace the secret while keeping the record, use &#x60;rotate_api_key&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateApiKeyTest() throws ApiException {
        String apiKeyId = null;
        ApiKeyPatchRequest apiKeyPatchRequest = null;
        ApiKeyDetailResponse response = api.updateApiKey(apiKeyId, apiKeyPatchRequest);
        // TODO: test validations
    }

}
