/*
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.BrandingProfileCreateRequest;
import org.openapitools.client.model.BrandingProfilePatchRequest;
import org.openapitools.client.model.BrandingProfileResponse;
import org.openapitools.client.model.BrandingProfilesListResponse;
import java.io.File;
import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.SimpleBoolResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BrandingProfilesApi
 */
@Disabled
public class BrandingProfilesApiTest {

    private final BrandingProfilesApi api = new BrandingProfilesApi();

    /**
     * Create Profile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProfileApiV1BrandingProfilesPostTest() throws ApiException {
        BrandingProfileCreateRequest brandingProfileCreateRequest = null;
        BrandingProfileResponse response = api.createProfileApiV1BrandingProfilesPost(brandingProfileCreateRequest);
        // TODO: test validations
    }

    /**
     * Delete Logo
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteLogoApiV1BrandingProfilesProfileIdLogoDeleteTest() throws ApiException {
        String profileId = null;
        SimpleBoolResponse response = api.deleteLogoApiV1BrandingProfilesProfileIdLogoDelete(profileId);
        // TODO: test validations
    }

    /**
     * Delete Profile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProfileApiV1BrandingProfilesProfileIdDeleteTest() throws ApiException {
        String profileId = null;
        SimpleBoolResponse response = api.deleteProfileApiV1BrandingProfilesProfileIdDelete(profileId);
        // TODO: test validations
    }

    /**
     * Get Profile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProfileApiV1BrandingProfilesProfileIdGetTest() throws ApiException {
        String profileId = null;
        BrandingProfileResponse response = api.getProfileApiV1BrandingProfilesProfileIdGet(profileId);
        // TODO: test validations
    }

    /**
     * List Profiles
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listProfilesApiV1BrandingProfilesGetTest() throws ApiException {
        BrandingProfilesListResponse response = api.listProfilesApiV1BrandingProfilesGet();
        // TODO: test validations
    }

    /**
     * Set Default
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setDefaultApiV1BrandingProfilesProfileIdDefaultPostTest() throws ApiException {
        String profileId = null;
        BrandingProfileResponse response = api.setDefaultApiV1BrandingProfilesProfileIdDefaultPost(profileId);
        // TODO: test validations
    }

    /**
     * Update Profile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProfileApiV1BrandingProfilesProfileIdPatchTest() throws ApiException {
        String profileId = null;
        BrandingProfilePatchRequest brandingProfilePatchRequest = null;
        BrandingProfileResponse response = api.updateProfileApiV1BrandingProfilesProfileIdPatch(profileId, brandingProfilePatchRequest);
        // TODO: test validations
    }

    /**
     * Upload Logo
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadLogoApiV1BrandingProfilesProfileIdLogoPostTest() throws ApiException {
        String profileId = null;
        File _file = null;
        BrandingProfileResponse response = api.uploadLogoApiV1BrandingProfilesProfileIdLogoPost(profileId, _file);
        // TODO: test validations
    }

}
