/*
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.CreditNoteCreateRequest;
import org.openapitools.client.model.CreditNoteRenderRequest;
import org.openapitools.client.model.CreditNoteResponse;
import org.openapitools.client.model.CreditNotesListResponse;
import org.openapitools.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CreditNotesApi
 */
@Disabled
public class CreditNotesApiTest {

    private final CreditNotesApi api = new CreditNotesApi();

    /**
     * Create Credit Note
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCreditNoteApiV1CreditNotesPostTest() throws ApiException {
        CreditNoteCreateRequest creditNoteCreateRequest = null;
        CreditNoteResponse response = api.createCreditNoteApiV1CreditNotesPost(creditNoteCreateRequest);
        // TODO: test validations
    }

    /**
     * Finalize Credit Note
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void finalizeCreditNoteApiV1CreditNotesCreditNoteIdFinalizePostTest() throws ApiException {
        String creditNoteId = null;
        CreditNoteResponse response = api.finalizeCreditNoteApiV1CreditNotesCreditNoteIdFinalizePost(creditNoteId);
        // TODO: test validations
    }

    /**
     * Get Credit Note
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCreditNoteApiV1CreditNotesCreditNoteIdGetTest() throws ApiException {
        String creditNoteId = null;
        CreditNoteResponse response = api.getCreditNoteApiV1CreditNotesCreditNoteIdGet(creditNoteId);
        // TODO: test validations
    }

    /**
     * List Credit Notes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCreditNotesApiV1CreditNotesGetTest() throws ApiException {
        Integer limit = null;
        String cursor = null;
        CreditNotesListResponse response = api.listCreditNotesApiV1CreditNotesGet(limit, cursor);
        // TODO: test validations
    }

    /**
     * Render Credit Note
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void renderCreditNoteApiV1CreditNotesCreditNoteIdRendersPostTest() throws ApiException {
        String creditNoteId = null;
        CreditNoteRenderRequest creditNoteRenderRequest = null;
        Object response = api.renderCreditNoteApiV1CreditNotesCreditNoteIdRendersPost(creditNoteId, creditNoteRenderRequest);
        // TODO: test validations
    }

}
