/*
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.ImportCreateRequest;
import org.openapitools.client.model.ImportResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImportsApi
 */
@Disabled
public class ImportsApiTest {

    private final ImportsApi api = new ImportsApi();

    /**
     * Cancel Import
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelImportApiV1ImportsImportIdCancelPostTest() throws ApiException {
        String importId = null;
        ImportResponse response = api.cancelImportApiV1ImportsImportIdCancelPost(importId);
        // TODO: test validations
    }

    /**
     * Confirm Import
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void confirmImportApiV1ImportsImportIdConfirmPostTest() throws ApiException {
        String importId = null;
        ImportResponse response = api.confirmImportApiV1ImportsImportIdConfirmPost(importId);
        // TODO: test validations
    }

    /**
     * Create Import
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createImportApiV1ImportsPostTest() throws ApiException {
        ImportCreateRequest importCreateRequest = null;
        ImportResponse response = api.createImportApiV1ImportsPost(importCreateRequest);
        // TODO: test validations
    }

    /**
     * Get Import
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getImportApiV1ImportsImportIdGetTest() throws ApiException {
        String importId = null;
        ImportResponse response = api.getImportApiV1ImportsImportIdGet(importId);
        // TODO: test validations
    }

}
