/*
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.ApiErrorResponse;
import org.openapitools.client.model.ImportCreateRequest;
import org.openapitools.client.model.ImportResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImportsApi
 */
@Disabled
public class ImportsApiTest {

    private final ImportsApi api = new ImportsApi();

    /**
     * Cancel Import
     *
     * Discard an import without creating anything. Only while it is &#x60;pending&#x60; or &#x60;processing&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelImportTest() throws ApiException {
        String importId = null;
        ImportResponse response = api.cancelImport(importId);
        // TODO: test validations
    }

    /**
     * Confirm Import
     *
     * Commit a reviewed import, creating its documents.  Only from &#x60;pending&#x60; — an import already confirmed or cancelled returns &#x60;409&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void confirmImportTest() throws ApiException {
        String importId = null;
        ImportResponse response = api.confirmImport(importId);
        // TODO: test validations
    }

    /**
     * Create Import
     *
     * Upload rows to be turned into documents, for review first.  Nothing is created yet: the rows are parsed and held so you can check them. &#x60;confirm_import&#x60; commits them, &#x60;cancel_import&#x60; discards them.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createImportTest() throws ApiException {
        ImportCreateRequest importCreateRequest = null;
        ImportResponse response = api.createImport(importCreateRequest);
        // TODO: test validations
    }

    /**
     * Get Import
     *
     * An import&#39;s status and how many rows it holds.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getImportTest() throws ApiException {
        String importId = null;
        ImportResponse response = api.getImport(importId);
        // TODO: test validations
    }

}
