/*
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.DeliveriesListResponse;
import org.openapitools.client.model.DeliveryResponse;
import org.openapitools.client.model.DeliverySendRequest;
import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.InvoiceCreateRequest;
import org.openapitools.client.model.InvoiceDraftRequest;
import org.openapitools.client.model.InvoicePatchRequest;
import org.openapitools.client.model.InvoicePreviewRequest;
import org.openapitools.client.model.InvoiceRenderRequest;
import org.openapitools.client.model.InvoiceResponse;
import org.openapitools.client.model.InvoicesListResponse;
import org.openapitools.client.model.SimpleBoolResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvoicesApi
 */
@Disabled
public class InvoicesApiTest {

    private final InvoicesApi api = new InvoicesApi();

    /**
     * Archive Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void archiveInvoiceApiV1InvoicesInvoiceIdArchivePostTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.archiveInvoiceApiV1InvoicesInvoiceIdArchivePost(invoiceId);
        // TODO: test validations
    }

    /**
     * Calculate Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void calculateInvoiceApiV1InvoicesCalculatePostTest() throws ApiException {
        InvoiceDraftRequest invoiceDraftRequest = null;
        Map<String, Object> response = api.calculateInvoiceApiV1InvoicesCalculatePost(invoiceDraftRequest);
        // TODO: test validations
    }

    /**
     * Create Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createInvoiceApiV1InvoicesPostTest() throws ApiException {
        InvoiceCreateRequest invoiceCreateRequest = null;
        String idempotencyKey = null;
        InvoiceResponse response = api.createInvoiceApiV1InvoicesPost(invoiceCreateRequest, idempotencyKey);
        // TODO: test validations
    }

    /**
     * Delete Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteInvoiceApiV1InvoicesInvoiceIdDeleteTest() throws ApiException {
        String invoiceId = null;
        SimpleBoolResponse response = api.deleteInvoiceApiV1InvoicesInvoiceIdDelete(invoiceId);
        // TODO: test validations
    }

    /**
     * Duplicate Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void duplicateInvoiceApiV1InvoicesInvoiceIdDuplicatePostTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.duplicateInvoiceApiV1InvoicesInvoiceIdDuplicatePost(invoiceId);
        // TODO: test validations
    }

    /**
     * Finalize Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void finalizeInvoiceApiV1InvoicesInvoiceIdFinalizePostTest() throws ApiException {
        String invoiceId = null;
        String idempotencyKey = null;
        Map<String, Object> response = api.finalizeInvoiceApiV1InvoicesInvoiceIdFinalizePost(invoiceId, idempotencyKey);
        // TODO: test validations
    }

    /**
     * Get Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInvoiceApiV1InvoicesInvoiceIdGetTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.getInvoiceApiV1InvoicesInvoiceIdGet(invoiceId);
        // TODO: test validations
    }

    /**
     * List Invoice Deliveries
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInvoiceDeliveriesApiV1InvoicesInvoiceIdDeliveriesGetTest() throws ApiException {
        String invoiceId = null;
        Integer limit = null;
        String cursor = null;
        DeliveriesListResponse response = api.listInvoiceDeliveriesApiV1InvoicesInvoiceIdDeliveriesGet(invoiceId, limit, cursor);
        // TODO: test validations
    }

    /**
     * List Invoices
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInvoicesApiV1InvoicesGetTest() throws ApiException {
        Integer limit = null;
        String cursor = null;
        String status = null;
        InvoicesListResponse response = api.listInvoicesApiV1InvoicesGet(limit, cursor, status);
        // TODO: test validations
    }

    /**
     * Mark Paid
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void markPaidApiV1InvoicesInvoiceIdMarkPaidPostTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.markPaidApiV1InvoicesInvoiceIdMarkPaidPost(invoiceId);
        // TODO: test validations
    }

    /**
     * Mark Sent
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void markSentApiV1InvoicesInvoiceIdMarkSentPostTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.markSentApiV1InvoicesInvoiceIdMarkSentPost(invoiceId);
        // TODO: test validations
    }

    /**
     * Mark Unpaid
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void markUnpaidApiV1InvoicesInvoiceIdMarkUnpaidPostTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.markUnpaidApiV1InvoicesInvoiceIdMarkUnpaidPost(invoiceId);
        // TODO: test validations
    }

    /**
     * Patch Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchInvoiceApiV1InvoicesInvoiceIdPatchTest() throws ApiException {
        String invoiceId = null;
        InvoicePatchRequest invoicePatchRequest = null;
        String idempotencyKey = null;
        InvoiceResponse response = api.patchInvoiceApiV1InvoicesInvoiceIdPatch(invoiceId, invoicePatchRequest, idempotencyKey);
        // TODO: test validations
    }

    /**
     * Preview Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void previewInvoiceApiV1InvoicesPreviewPostTest() throws ApiException {
        InvoicePreviewRequest invoicePreviewRequest = null;
        Object response = api.previewInvoiceApiV1InvoicesPreviewPost(invoicePreviewRequest);
        // TODO: test validations
    }

    /**
     * Render Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void renderInvoiceApiV1InvoicesInvoiceIdRendersPostTest() throws ApiException {
        String invoiceId = null;
        InvoiceRenderRequest invoiceRenderRequest = null;
        String idempotencyKey = null;
        Object response = api.renderInvoiceApiV1InvoicesInvoiceIdRendersPost(invoiceId, invoiceRenderRequest, idempotencyKey);
        // TODO: test validations
    }

    /**
     * Replace Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void replaceInvoiceApiV1InvoicesInvoiceIdPutTest() throws ApiException {
        String invoiceId = null;
        InvoiceCreateRequest invoiceCreateRequest = null;
        String idempotencyKey = null;
        InvoiceResponse response = api.replaceInvoiceApiV1InvoicesInvoiceIdPut(invoiceId, invoiceCreateRequest, idempotencyKey);
        // TODO: test validations
    }

    /**
     * Restore Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void restoreInvoiceApiV1InvoicesInvoiceIdRestorePostTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.restoreInvoiceApiV1InvoicesInvoiceIdRestorePost(invoiceId);
        // TODO: test validations
    }

    /**
     * Send Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendInvoiceApiV1InvoicesInvoiceIdSendPostTest() throws ApiException {
        String invoiceId = null;
        DeliverySendRequest deliverySendRequest = null;
        DeliveryResponse response = api.sendInvoiceApiV1InvoicesInvoiceIdSendPost(invoiceId, deliverySendRequest);
        // TODO: test validations
    }

    /**
     * Validate Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void validateInvoiceApiV1InvoicesValidatePostTest() throws ApiException {
        InvoiceDraftRequest invoiceDraftRequest = null;
        Map<String, Object> response = api.validateInvoiceApiV1InvoicesValidatePost(invoiceDraftRequest);
        // TODO: test validations
    }

    /**
     * Void Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void voidInvoiceApiV1InvoicesInvoiceIdVoidPostTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.voidInvoiceApiV1InvoicesInvoiceIdVoidPost(invoiceId);
        // TODO: test validations
    }

}
