/*
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.PaymentCreateRequest;
import org.openapitools.client.model.PaymentPatchRequest;
import org.openapitools.client.model.PaymentResponse;
import org.openapitools.client.model.PaymentsListResponse;
import org.openapitools.client.model.SimpleBoolResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentsApi
 */
@Disabled
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    /**
     * Create Payment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPaymentApiV1InvoicesInvoiceIdPaymentsPostTest() throws ApiException {
        String invoiceId = null;
        PaymentCreateRequest paymentCreateRequest = null;
        PaymentResponse response = api.createPaymentApiV1InvoicesInvoiceIdPaymentsPost(invoiceId, paymentCreateRequest);
        // TODO: test validations
    }

    /**
     * Delete Payment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePaymentApiV1PaymentsPaymentIdDeleteTest() throws ApiException {
        String paymentId = null;
        SimpleBoolResponse response = api.deletePaymentApiV1PaymentsPaymentIdDelete(paymentId);
        // TODO: test validations
    }

    /**
     * Get Payment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaymentApiV1PaymentsPaymentIdGetTest() throws ApiException {
        String paymentId = null;
        PaymentResponse response = api.getPaymentApiV1PaymentsPaymentIdGet(paymentId);
        // TODO: test validations
    }

    /**
     * List Invoice Payments
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInvoicePaymentsApiV1InvoicesInvoiceIdPaymentsGetTest() throws ApiException {
        String invoiceId = null;
        Integer limit = null;
        String cursor = null;
        PaymentsListResponse response = api.listInvoicePaymentsApiV1InvoicesInvoiceIdPaymentsGet(invoiceId, limit, cursor);
        // TODO: test validations
    }

    /**
     * Update Payment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePaymentApiV1PaymentsPaymentIdPatchTest() throws ApiException {
        String paymentId = null;
        PaymentPatchRequest paymentPatchRequest = null;
        PaymentResponse response = api.updatePaymentApiV1PaymentsPaymentIdPatch(paymentId, paymentPatchRequest);
        // TODO: test validations
    }

}
