/*
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReferenceApi
 */
@Disabled
public class ReferenceApiTest {

    private final ReferenceApi api = new ReferenceApi();

    /**
     * List Countries
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCountriesApiV1ReferenceCountriesGetTest() throws ApiException {
        Map<String, Object> response = api.listCountriesApiV1ReferenceCountriesGet();
        // TODO: test validations
    }

    /**
     * List Currencies
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCurrenciesApiV1ReferenceCurrenciesGetTest() throws ApiException {
        Map<String, Object> response = api.listCurrenciesApiV1ReferenceCurrenciesGet();
        // TODO: test validations
    }

    /**
     * List Document Types
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listDocumentTypesApiV1ReferenceDocumentTypesGetTest() throws ApiException {
        Map<String, Object> response = api.listDocumentTypesApiV1ReferenceDocumentTypesGet();
        // TODO: test validations
    }

    /**
     * List Locales
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listLocalesApiV1ReferenceLocalesGetTest() throws ApiException {
        Map<String, Object> response = api.listLocalesApiV1ReferenceLocalesGet();
        // TODO: test validations
    }

    /**
     * List Page Sizes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listPageSizesApiV1ReferencePageSizesGetTest() throws ApiException {
        Map<String, Object> response = api.listPageSizesApiV1ReferencePageSizesGet();
        // TODO: test validations
    }

    /**
     * List Timezones
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTimezonesApiV1ReferenceTimezonesGetTest() throws ApiException {
        Map<String, Object> response = api.listTimezonesApiV1ReferenceTimezonesGet();
        // TODO: test validations
    }

}
