/*
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.ApiErrorResponse;
import java.io.File;
import org.openapitools.client.model.RenderResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RendersApi
 */
@Disabled
public class RendersApiTest {

    private final RendersApi api = new RendersApi();

    /**
     * Download Render
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadRenderTest() throws ApiException {
        String renderId = null;
        File response = api.downloadRender(renderId);
        // TODO: test validations
    }

    /**
     * Get Render
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRenderTest() throws ApiException {
        String renderId = null;
        RenderResponse response = api.getRender(renderId);
        // TODO: test validations
    }

}
