/*
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.SimpleBoolResponse;
import org.openapitools.client.model.TaxRateCreateRequest;
import org.openapitools.client.model.TaxRatePatchRequest;
import org.openapitools.client.model.TaxRateResponse;
import org.openapitools.client.model.TaxRatesListResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TaxRatesApi
 */
@Disabled
public class TaxRatesApiTest {

    private final TaxRatesApi api = new TaxRatesApi();

    /**
     * Create Tax Rate
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTaxRateApiV1TaxRatesPostTest() throws ApiException {
        TaxRateCreateRequest taxRateCreateRequest = null;
        TaxRateResponse response = api.createTaxRateApiV1TaxRatesPost(taxRateCreateRequest);
        // TODO: test validations
    }

    /**
     * Delete Tax Rate
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTaxRateApiV1TaxRatesTaxRateIdDeleteTest() throws ApiException {
        String taxRateId = null;
        SimpleBoolResponse response = api.deleteTaxRateApiV1TaxRatesTaxRateIdDelete(taxRateId);
        // TODO: test validations
    }

    /**
     * Get Tax Rate
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTaxRateApiV1TaxRatesTaxRateIdGetTest() throws ApiException {
        String taxRateId = null;
        TaxRateResponse response = api.getTaxRateApiV1TaxRatesTaxRateIdGet(taxRateId);
        // TODO: test validations
    }

    /**
     * List Tax Rates
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTaxRatesApiV1TaxRatesGetTest() throws ApiException {
        Integer limit = null;
        String cursor = null;
        TaxRatesListResponse response = api.listTaxRatesApiV1TaxRatesGet(limit, cursor);
        // TODO: test validations
    }

    /**
     * Update Tax Rate
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTaxRateApiV1TaxRatesTaxRateIdPatchTest() throws ApiException {
        String taxRateId = null;
        TaxRatePatchRequest taxRatePatchRequest = null;
        TaxRateResponse response = api.updateTaxRateApiV1TaxRatesTaxRateIdPatch(taxRateId, taxRatePatchRequest);
        // TODO: test validations
    }

}
