/*
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.UsageResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsageApi
 */
@Disabled
public class UsageApiTest {

    private final UsageApi api = new UsageApi();

    /**
     * Get Limits
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLimitsApiV1UsageLimitsGetTest() throws ApiException {
        Map<String, Object> response = api.getLimitsApiV1UsageLimitsGet();
        // TODO: test validations
    }

    /**
     * List Usage Events
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listUsageEventsApiV1UsageEventsGetTest() throws ApiException {
        Integer limit = null;
        String cursor = null;
        Map<String, Object> response = api.listUsageEventsApiV1UsageEventsGet(limit, cursor);
        // TODO: test validations
    }

    /**
     * Usage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usageApiV1UsageGetTest() throws ApiException {
        UsageResponse response = api.usageApiV1UsageGet();
        // TODO: test validations
    }

}
