/*
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.invoicepdfs.ApiException;
import org.openapitools.client.model.ApiErrorResponse;
import org.openapitools.client.model.SimpleBoolResponse;
import org.openapitools.client.model.WorkspaceCreateRequest;
import org.openapitools.client.model.WorkspaceMemberCreateRequest;
import org.openapitools.client.model.WorkspaceMemberOut;
import org.openapitools.client.model.WorkspaceMemberPatchRequest;
import org.openapitools.client.model.WorkspaceMembersListResponse;
import org.openapitools.client.model.WorkspacePatchRequest;
import org.openapitools.client.model.WorkspaceResponse;
import org.openapitools.client.model.WorkspacesListResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkspacesApi
 */
@Disabled
public class WorkspacesApiTest {

    private final WorkspacesApi api = new WorkspacesApi();

    /**
     * Add Workspace Member
     *
     * Add someone to a workspace by email address.  Refused with 409 if that email is already a member. The address does not have to belong to an existing account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addWorkspaceMemberTest() throws ApiException {
        String workspaceId = null;
        WorkspaceMemberCreateRequest workspaceMemberCreateRequest = null;
        String idempotencyKey = null;
        WorkspaceMembersListResponse response = api.addWorkspaceMember(workspaceId, workspaceMemberCreateRequest, idempotencyKey);
        // TODO: test validations
    }

    /**
     * Create Workspace
     *
     * Create a workspace, owned by this account.  The creating account is added as its first member with the &#x60;owner&#x60; role.  Send an &#x60;Idempotency-Key&#x60; header to make retrying safe: a repeat with the same key and body returns the original workspace instead of a second one.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createWorkspaceTest() throws ApiException {
        WorkspaceCreateRequest workspaceCreateRequest = null;
        String idempotencyKey = null;
        WorkspaceResponse response = api.createWorkspace(workspaceCreateRequest, idempotencyKey);
        // TODO: test validations
    }

    /**
     * Delete Workspace
     *
     * Delete a workspace and its membership list.  Every member record goes with it. This cannot be undone, and documents are unaffected — they belong to the account, not the workspace.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteWorkspaceTest() throws ApiException {
        String workspaceId = null;
        SimpleBoolResponse response = api.deleteWorkspace(workspaceId);
        // TODO: test validations
    }

    /**
     * Get Workspace
     *
     * One workspace by id.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWorkspaceTest() throws ApiException {
        String workspaceId = null;
        WorkspaceResponse response = api.getWorkspace(workspaceId);
        // TODO: test validations
    }

    /**
     * List Workspace Members
     *
     * Everyone on a workspace, with their role.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listWorkspaceMembersTest() throws ApiException {
        String workspaceId = null;
        WorkspaceMembersListResponse response = api.listWorkspaceMembers(workspaceId);
        // TODO: test validations
    }

    /**
     * List Workspaces
     *
     * Workspaces this account owns, newest first.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listWorkspacesTest() throws ApiException {
        Integer limit = null;
        String cursor = null;
        WorkspacesListResponse response = api.listWorkspaces(limit, cursor);
        // TODO: test validations
    }

    /**
     * Remove Workspace Member
     *
     * Remove someone from a workspace.  Removes the membership only; nothing they created is affected.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeWorkspaceMemberTest() throws ApiException {
        String workspaceId = null;
        String memberId = null;
        SimpleBoolResponse response = api.removeWorkspaceMember(workspaceId, memberId);
        // TODO: test validations
    }

    /**
     * Update Workspace
     *
     * Rename a workspace.  Only the fields you send are changed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateWorkspaceTest() throws ApiException {
        String workspaceId = null;
        WorkspacePatchRequest workspacePatchRequest = null;
        String idempotencyKey = null;
        WorkspaceResponse response = api.updateWorkspace(workspaceId, workspacePatchRequest, idempotencyKey);
        // TODO: test validations
    }

    /**
     * Update Workspace Member
     *
     * Change a member&#39;s role.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateWorkspaceMemberTest() throws ApiException {
        String workspaceId = null;
        String memberId = null;
        WorkspaceMemberPatchRequest workspaceMemberPatchRequest = null;
        WorkspaceMemberOut response = api.updateWorkspaceMember(workspaceId, memberId, workspaceMemberPatchRequest);
        // TODO: test validations
    }

}
